### ISSUE TITLE
It seems works only with Faye 1.1.2, not with later versions

### ISSUE THREAD

**Issue by ukolovda** [dimelo/faye-authentication#9]
With latest Faye 1.2.0 and later I got error on line:
`Faye.extend(FayeAuthentication.prototype, Faye.Logging);`
(Faye.extend is not a function)

And after I comment this line, it fail on
`var promise = self._signatures[clientId][channel] = new Faye.Promise();`

**Comment by jarthod** [comment]
Indeed we'll need to have a look a this but that's low priority.
If you need this compatibility you'll have to write a PR :)

**Comment by FabienChaynes** [comment]
Handled by #10.
